package xyz.nuze.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xyz.nuze.model.Booking;
import xyz.nuze.model.BookingExample;

public interface BookingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    long countByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    int deleteByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    int insert(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    int insertSelective(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    List<Booking> selectByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    Booking selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    int updateByExampleSelective(@Param("record") Booking record, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    int updateByExample(@Param("record") Booking record, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    int updateByPrimaryKeySelective(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbg.generated Fri Aug 02 21:04:25 AEST 2019
     */
    int updateByPrimaryKey(Booking record);
}