package xyz.nuze.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xyz.nuze.model.HousePicUrls;
import xyz.nuze.model.HousePicUrlsExample;

public interface HousePicUrlsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    long countByExample(HousePicUrlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    int deleteByExample(HousePicUrlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    int insert(HousePicUrls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    int insertSelective(HousePicUrls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    List<HousePicUrls> selectByExample(HousePicUrlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    HousePicUrls selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    int updateByExampleSelective(@Param("record") HousePicUrls record, @Param("example") HousePicUrlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    int updateByExample(@Param("record") HousePicUrls record, @Param("example") HousePicUrlsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    int updateByPrimaryKeySelective(HousePicUrls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_pic_urls
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    int updateByPrimaryKey(HousePicUrls record);
}