package xyz.nuze.model;

import java.util.Date;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.user_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_name
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.create_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.update_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_id
     *
     * @return the value of client.client_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_id
     *
     * @param clientId the value for client.client_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.user_id
     *
     * @return the value of client.user_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.user_id
     *
     * @param userId the value for client.user_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_name
     *
     * @return the value of client.client_name
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_name
     *
     * @param clientName the value for client.client_name
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.create_time
     *
     * @return the value of client.create_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.create_time
     *
     * @param createTime the value for client.create_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.update_time
     *
     * @return the value of client.update_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.update_time
     *
     * @param updateTime the value for client.update_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}