package xyz.nuze.model;

import java.util.Date;

public class Host {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private Integer hostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.user_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.name
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.details
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private String details;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.pic_url
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.self_intro
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private String selfIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.create_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.update_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_id
     *
     * @return the value of host.host_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public Integer getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_id
     *
     * @param hostId the value for host.host_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setHostId(Integer hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.user_id
     *
     * @return the value of host.user_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.user_id
     *
     * @param userId the value for host.user_id
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.name
     *
     * @return the value of host.name
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.name
     *
     * @param name the value for host.name
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.details
     *
     * @return the value of host.details
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.details
     *
     * @param details the value for host.details
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.pic_url
     *
     * @return the value of host.pic_url
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.pic_url
     *
     * @param picUrl the value for host.pic_url
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.self_intro
     *
     * @return the value of host.self_intro
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public String getSelfIntro() {
        return selfIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.self_intro
     *
     * @param selfIntro the value for host.self_intro
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setSelfIntro(String selfIntro) {
        this.selfIntro = selfIntro == null ? null : selfIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.create_time
     *
     * @return the value of host.create_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.create_time
     *
     * @param createTime the value for host.create_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.update_time
     *
     * @return the value of host.update_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.update_time
     *
     * @param updateTime the value for host.update_time
     *
     * @mbg.generated Sun Jun 30 16:10:46 AEST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}