package xyz.nuze.model;

public class Host {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Host
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Db
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String db;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Select_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String selectPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Insert_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String insertPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Update_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String updatePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Delete_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String deletePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Create_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String createPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Drop_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String dropPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Grant_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String grantPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.References_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String referencesPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Index_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String indexPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Alter_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String alterPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Create_tmp_table_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String createTmpTablePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Lock_tables_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String lockTablesPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Create_view_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String createViewPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Show_view_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String showViewPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Create_routine_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String createRoutinePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Alter_routine_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String alterRoutinePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Execute_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String executePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.Trigger_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    private String triggerPriv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Host
     *
     * @return the value of host.Host
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Host
     *
     * @param host the value for host.Host
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Db
     *
     * @return the value of host.Db
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getDb() {
        return db;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Db
     *
     * @param db the value for host.Db
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setDb(String db) {
        this.db = db == null ? null : db.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Select_priv
     *
     * @return the value of host.Select_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getSelectPriv() {
        return selectPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Select_priv
     *
     * @param selectPriv the value for host.Select_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setSelectPriv(String selectPriv) {
        this.selectPriv = selectPriv == null ? null : selectPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Insert_priv
     *
     * @return the value of host.Insert_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getInsertPriv() {
        return insertPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Insert_priv
     *
     * @param insertPriv the value for host.Insert_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setInsertPriv(String insertPriv) {
        this.insertPriv = insertPriv == null ? null : insertPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Update_priv
     *
     * @return the value of host.Update_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getUpdatePriv() {
        return updatePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Update_priv
     *
     * @param updatePriv the value for host.Update_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setUpdatePriv(String updatePriv) {
        this.updatePriv = updatePriv == null ? null : updatePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Delete_priv
     *
     * @return the value of host.Delete_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getDeletePriv() {
        return deletePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Delete_priv
     *
     * @param deletePriv the value for host.Delete_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setDeletePriv(String deletePriv) {
        this.deletePriv = deletePriv == null ? null : deletePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Create_priv
     *
     * @return the value of host.Create_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getCreatePriv() {
        return createPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Create_priv
     *
     * @param createPriv the value for host.Create_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setCreatePriv(String createPriv) {
        this.createPriv = createPriv == null ? null : createPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Drop_priv
     *
     * @return the value of host.Drop_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getDropPriv() {
        return dropPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Drop_priv
     *
     * @param dropPriv the value for host.Drop_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setDropPriv(String dropPriv) {
        this.dropPriv = dropPriv == null ? null : dropPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Grant_priv
     *
     * @return the value of host.Grant_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getGrantPriv() {
        return grantPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Grant_priv
     *
     * @param grantPriv the value for host.Grant_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setGrantPriv(String grantPriv) {
        this.grantPriv = grantPriv == null ? null : grantPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.References_priv
     *
     * @return the value of host.References_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getReferencesPriv() {
        return referencesPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.References_priv
     *
     * @param referencesPriv the value for host.References_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setReferencesPriv(String referencesPriv) {
        this.referencesPriv = referencesPriv == null ? null : referencesPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Index_priv
     *
     * @return the value of host.Index_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getIndexPriv() {
        return indexPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Index_priv
     *
     * @param indexPriv the value for host.Index_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setIndexPriv(String indexPriv) {
        this.indexPriv = indexPriv == null ? null : indexPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Alter_priv
     *
     * @return the value of host.Alter_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getAlterPriv() {
        return alterPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Alter_priv
     *
     * @param alterPriv the value for host.Alter_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setAlterPriv(String alterPriv) {
        this.alterPriv = alterPriv == null ? null : alterPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Create_tmp_table_priv
     *
     * @return the value of host.Create_tmp_table_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getCreateTmpTablePriv() {
        return createTmpTablePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Create_tmp_table_priv
     *
     * @param createTmpTablePriv the value for host.Create_tmp_table_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setCreateTmpTablePriv(String createTmpTablePriv) {
        this.createTmpTablePriv = createTmpTablePriv == null ? null : createTmpTablePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Lock_tables_priv
     *
     * @return the value of host.Lock_tables_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getLockTablesPriv() {
        return lockTablesPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Lock_tables_priv
     *
     * @param lockTablesPriv the value for host.Lock_tables_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setLockTablesPriv(String lockTablesPriv) {
        this.lockTablesPriv = lockTablesPriv == null ? null : lockTablesPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Create_view_priv
     *
     * @return the value of host.Create_view_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getCreateViewPriv() {
        return createViewPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Create_view_priv
     *
     * @param createViewPriv the value for host.Create_view_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setCreateViewPriv(String createViewPriv) {
        this.createViewPriv = createViewPriv == null ? null : createViewPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Show_view_priv
     *
     * @return the value of host.Show_view_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getShowViewPriv() {
        return showViewPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Show_view_priv
     *
     * @param showViewPriv the value for host.Show_view_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setShowViewPriv(String showViewPriv) {
        this.showViewPriv = showViewPriv == null ? null : showViewPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Create_routine_priv
     *
     * @return the value of host.Create_routine_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getCreateRoutinePriv() {
        return createRoutinePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Create_routine_priv
     *
     * @param createRoutinePriv the value for host.Create_routine_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setCreateRoutinePriv(String createRoutinePriv) {
        this.createRoutinePriv = createRoutinePriv == null ? null : createRoutinePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Alter_routine_priv
     *
     * @return the value of host.Alter_routine_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getAlterRoutinePriv() {
        return alterRoutinePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Alter_routine_priv
     *
     * @param alterRoutinePriv the value for host.Alter_routine_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setAlterRoutinePriv(String alterRoutinePriv) {
        this.alterRoutinePriv = alterRoutinePriv == null ? null : alterRoutinePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Execute_priv
     *
     * @return the value of host.Execute_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getExecutePriv() {
        return executePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Execute_priv
     *
     * @param executePriv the value for host.Execute_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setExecutePriv(String executePriv) {
        this.executePriv = executePriv == null ? null : executePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.Trigger_priv
     *
     * @return the value of host.Trigger_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public String getTriggerPriv() {
        return triggerPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.Trigger_priv
     *
     * @param triggerPriv the value for host.Trigger_priv
     *
     * @mbg.generated Sun Jun 30 15:11:14 AEST 2019
     */
    public void setTriggerPriv(String triggerPriv) {
        this.triggerPriv = triggerPriv == null ? null : triggerPriv.trim();
    }
}