package xyz.nuze.model;

public class HouseReview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_review.id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_review.house_id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    private Integer houseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_review.client_id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_review.host_id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    private Integer hostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_review.comment
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_review.id
     *
     * @return the value of house_review.id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_review.id
     *
     * @param id the value for house_review.id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_review.house_id
     *
     * @return the value of house_review.house_id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_review.house_id
     *
     * @param houseId the value for house_review.house_id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_review.client_id
     *
     * @return the value of house_review.client_id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_review.client_id
     *
     * @param clientId the value for house_review.client_id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_review.host_id
     *
     * @return the value of house_review.host_id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public Integer getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_review.host_id
     *
     * @param hostId the value for house_review.host_id
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public void setHostId(Integer hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_review.comment
     *
     * @return the value of house_review.comment
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_review.comment
     *
     * @param comment the value for house_review.comment
     *
     * @mbg.generated Fri Jul 19 11:57:50 AEST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}