package xyz.nuze.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HouseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public HouseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHouseIdIsNull() {
            addCriterion("house_id is null");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNotNull() {
            addCriterion("house_id is not null");
            return (Criteria) this;
        }

        public Criteria andHouseIdEqualTo(Integer value) {
            addCriterion("house_id =", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotEqualTo(Integer value) {
            addCriterion("house_id <>", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThan(Integer value) {
            addCriterion("house_id >", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("house_id >=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThan(Integer value) {
            addCriterion("house_id <", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThanOrEqualTo(Integer value) {
            addCriterion("house_id <=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdIn(List<Integer> values) {
            addCriterion("house_id in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotIn(List<Integer> values) {
            addCriterion("house_id not in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdBetween(Integer value1, Integer value2) {
            addCriterion("house_id between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("house_id not between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andHostIdIsNull() {
            addCriterion("host_id is null");
            return (Criteria) this;
        }

        public Criteria andHostIdIsNotNull() {
            addCriterion("host_id is not null");
            return (Criteria) this;
        }

        public Criteria andHostIdEqualTo(Integer value) {
            addCriterion("host_id =", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotEqualTo(Integer value) {
            addCriterion("host_id <>", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdGreaterThan(Integer value) {
            addCriterion("host_id >", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("host_id >=", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdLessThan(Integer value) {
            addCriterion("host_id <", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdLessThanOrEqualTo(Integer value) {
            addCriterion("host_id <=", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdIn(List<Integer> values) {
            addCriterion("host_id in", values, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotIn(List<Integer> values) {
            addCriterion("host_id not in", values, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdBetween(Integer value1, Integer value2) {
            addCriterion("host_id between", value1, value2, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotBetween(Integer value1, Integer value2) {
            addCriterion("host_id not between", value1, value2, "hostId");
            return (Criteria) this;
        }

        public Criteria andLatIsNull() {
            addCriterion("lat is null");
            return (Criteria) this;
        }

        public Criteria andLatIsNotNull() {
            addCriterion("lat is not null");
            return (Criteria) this;
        }

        public Criteria andLatEqualTo(Double value) {
            addCriterion("lat =", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotEqualTo(Double value) {
            addCriterion("lat <>", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThan(Double value) {
            addCriterion("lat >", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThanOrEqualTo(Double value) {
            addCriterion("lat >=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThan(Double value) {
            addCriterion("lat <", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThanOrEqualTo(Double value) {
            addCriterion("lat <=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatIn(List<Double> values) {
            addCriterion("lat in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotIn(List<Double> values) {
            addCriterion("lat not in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatBetween(Double value1, Double value2) {
            addCriterion("lat between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotBetween(Double value1, Double value2) {
            addCriterion("lat not between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLngIsNull() {
            addCriterion("lng is null");
            return (Criteria) this;
        }

        public Criteria andLngIsNotNull() {
            addCriterion("lng is not null");
            return (Criteria) this;
        }

        public Criteria andLngEqualTo(Double value) {
            addCriterion("lng =", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotEqualTo(Double value) {
            addCriterion("lng <>", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThan(Double value) {
            addCriterion("lng >", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThanOrEqualTo(Double value) {
            addCriterion("lng >=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThan(Double value) {
            addCriterion("lng <", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThanOrEqualTo(Double value) {
            addCriterion("lng <=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngIn(List<Double> values) {
            addCriterion("lng in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotIn(List<Double> values) {
            addCriterion("lng not in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngBetween(Double value1, Double value2) {
            addCriterion("lng between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotBetween(Double value1, Double value2) {
            addCriterion("lng not between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andBrifeInforIsNull() {
            addCriterion("brife_infor is null");
            return (Criteria) this;
        }

        public Criteria andBrifeInforIsNotNull() {
            addCriterion("brife_infor is not null");
            return (Criteria) this;
        }

        public Criteria andBrifeInforEqualTo(String value) {
            addCriterion("brife_infor =", value, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforNotEqualTo(String value) {
            addCriterion("brife_infor <>", value, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforGreaterThan(String value) {
            addCriterion("brife_infor >", value, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforGreaterThanOrEqualTo(String value) {
            addCriterion("brife_infor >=", value, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforLessThan(String value) {
            addCriterion("brife_infor <", value, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforLessThanOrEqualTo(String value) {
            addCriterion("brife_infor <=", value, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforLike(String value) {
            addCriterion("brife_infor like", value, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforNotLike(String value) {
            addCriterion("brife_infor not like", value, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforIn(List<String> values) {
            addCriterion("brife_infor in", values, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforNotIn(List<String> values) {
            addCriterion("brife_infor not in", values, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforBetween(String value1, String value2) {
            addCriterion("brife_infor between", value1, value2, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andBrifeInforNotBetween(String value1, String value2) {
            addCriterion("brife_infor not between", value1, value2, "brifeInfor");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andBedroomsIsNull() {
            addCriterion("bedrooms is null");
            return (Criteria) this;
        }

        public Criteria andBedroomsIsNotNull() {
            addCriterion("bedrooms is not null");
            return (Criteria) this;
        }

        public Criteria andBedroomsEqualTo(Integer value) {
            addCriterion("bedrooms =", value, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBedroomsNotEqualTo(Integer value) {
            addCriterion("bedrooms <>", value, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBedroomsGreaterThan(Integer value) {
            addCriterion("bedrooms >", value, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBedroomsGreaterThanOrEqualTo(Integer value) {
            addCriterion("bedrooms >=", value, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBedroomsLessThan(Integer value) {
            addCriterion("bedrooms <", value, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBedroomsLessThanOrEqualTo(Integer value) {
            addCriterion("bedrooms <=", value, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBedroomsIn(List<Integer> values) {
            addCriterion("bedrooms in", values, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBedroomsNotIn(List<Integer> values) {
            addCriterion("bedrooms not in", values, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBedroomsBetween(Integer value1, Integer value2) {
            addCriterion("bedrooms between", value1, value2, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBedroomsNotBetween(Integer value1, Integer value2) {
            addCriterion("bedrooms not between", value1, value2, "bedrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsIsNull() {
            addCriterion("bathrooms is null");
            return (Criteria) this;
        }

        public Criteria andBathroomsIsNotNull() {
            addCriterion("bathrooms is not null");
            return (Criteria) this;
        }

        public Criteria andBathroomsEqualTo(Integer value) {
            addCriterion("bathrooms =", value, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsNotEqualTo(Integer value) {
            addCriterion("bathrooms <>", value, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsGreaterThan(Integer value) {
            addCriterion("bathrooms >", value, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsGreaterThanOrEqualTo(Integer value) {
            addCriterion("bathrooms >=", value, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsLessThan(Integer value) {
            addCriterion("bathrooms <", value, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsLessThanOrEqualTo(Integer value) {
            addCriterion("bathrooms <=", value, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsIn(List<Integer> values) {
            addCriterion("bathrooms in", values, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsNotIn(List<Integer> values) {
            addCriterion("bathrooms not in", values, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsBetween(Integer value1, Integer value2) {
            addCriterion("bathrooms between", value1, value2, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBathroomsNotBetween(Integer value1, Integer value2) {
            addCriterion("bathrooms not between", value1, value2, "bathrooms");
            return (Criteria) this;
        }

        public Criteria andBedsIsNull() {
            addCriterion("beds is null");
            return (Criteria) this;
        }

        public Criteria andBedsIsNotNull() {
            addCriterion("beds is not null");
            return (Criteria) this;
        }

        public Criteria andBedsEqualTo(Integer value) {
            addCriterion("beds =", value, "beds");
            return (Criteria) this;
        }

        public Criteria andBedsNotEqualTo(Integer value) {
            addCriterion("beds <>", value, "beds");
            return (Criteria) this;
        }

        public Criteria andBedsGreaterThan(Integer value) {
            addCriterion("beds >", value, "beds");
            return (Criteria) this;
        }

        public Criteria andBedsGreaterThanOrEqualTo(Integer value) {
            addCriterion("beds >=", value, "beds");
            return (Criteria) this;
        }

        public Criteria andBedsLessThan(Integer value) {
            addCriterion("beds <", value, "beds");
            return (Criteria) this;
        }

        public Criteria andBedsLessThanOrEqualTo(Integer value) {
            addCriterion("beds <=", value, "beds");
            return (Criteria) this;
        }

        public Criteria andBedsIn(List<Integer> values) {
            addCriterion("beds in", values, "beds");
            return (Criteria) this;
        }

        public Criteria andBedsNotIn(List<Integer> values) {
            addCriterion("beds not in", values, "beds");
            return (Criteria) this;
        }

        public Criteria andBedsBetween(Integer value1, Integer value2) {
            addCriterion("beds between", value1, value2, "beds");
            return (Criteria) this;
        }

        public Criteria andBedsNotBetween(Integer value1, Integer value2) {
            addCriterion("beds not between", value1, value2, "beds");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityIsNull() {
            addCriterion("guest_capacity is null");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityIsNotNull() {
            addCriterion("guest_capacity is not null");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityEqualTo(Integer value) {
            addCriterion("guest_capacity =", value, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityNotEqualTo(Integer value) {
            addCriterion("guest_capacity <>", value, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityGreaterThan(Integer value) {
            addCriterion("guest_capacity >", value, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityGreaterThanOrEqualTo(Integer value) {
            addCriterion("guest_capacity >=", value, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityLessThan(Integer value) {
            addCriterion("guest_capacity <", value, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityLessThanOrEqualTo(Integer value) {
            addCriterion("guest_capacity <=", value, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityIn(List<Integer> values) {
            addCriterion("guest_capacity in", values, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityNotIn(List<Integer> values) {
            addCriterion("guest_capacity not in", values, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityBetween(Integer value1, Integer value2) {
            addCriterion("guest_capacity between", value1, value2, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andGuestCapacityNotBetween(Integer value1, Integer value2) {
            addCriterion("guest_capacity not between", value1, value2, "guestCapacity");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodIsNull() {
            addCriterion("neighborhood is null");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodIsNotNull() {
            addCriterion("neighborhood is not null");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodEqualTo(String value) {
            addCriterion("neighborhood =", value, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodNotEqualTo(String value) {
            addCriterion("neighborhood <>", value, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodGreaterThan(String value) {
            addCriterion("neighborhood >", value, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodGreaterThanOrEqualTo(String value) {
            addCriterion("neighborhood >=", value, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodLessThan(String value) {
            addCriterion("neighborhood <", value, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodLessThanOrEqualTo(String value) {
            addCriterion("neighborhood <=", value, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodLike(String value) {
            addCriterion("neighborhood like", value, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodNotLike(String value) {
            addCriterion("neighborhood not like", value, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodIn(List<String> values) {
            addCriterion("neighborhood in", values, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodNotIn(List<String> values) {
            addCriterion("neighborhood not in", values, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodBetween(String value1, String value2) {
            addCriterion("neighborhood between", value1, value2, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andNeighborhoodNotBetween(String value1, String value2) {
            addCriterion("neighborhood not between", value1, value2, "neighborhood");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesIsNull() {
            addCriterion("preview_amenities is null");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesIsNotNull() {
            addCriterion("preview_amenities is not null");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesEqualTo(String value) {
            addCriterion("preview_amenities =", value, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesNotEqualTo(String value) {
            addCriterion("preview_amenities <>", value, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesGreaterThan(String value) {
            addCriterion("preview_amenities >", value, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesGreaterThanOrEqualTo(String value) {
            addCriterion("preview_amenities >=", value, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesLessThan(String value) {
            addCriterion("preview_amenities <", value, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesLessThanOrEqualTo(String value) {
            addCriterion("preview_amenities <=", value, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesLike(String value) {
            addCriterion("preview_amenities like", value, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesNotLike(String value) {
            addCriterion("preview_amenities not like", value, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesIn(List<String> values) {
            addCriterion("preview_amenities in", values, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesNotIn(List<String> values) {
            addCriterion("preview_amenities not in", values, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesBetween(String value1, String value2) {
            addCriterion("preview_amenities between", value1, value2, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andPreviewAmenitiesNotBetween(String value1, String value2) {
            addCriterion("preview_amenities not between", value1, value2, "previewAmenities");
            return (Criteria) this;
        }

        public Criteria andReviewsCountIsNull() {
            addCriterion("reviews_count is null");
            return (Criteria) this;
        }

        public Criteria andReviewsCountIsNotNull() {
            addCriterion("reviews_count is not null");
            return (Criteria) this;
        }

        public Criteria andReviewsCountEqualTo(Integer value) {
            addCriterion("reviews_count =", value, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andReviewsCountNotEqualTo(Integer value) {
            addCriterion("reviews_count <>", value, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andReviewsCountGreaterThan(Integer value) {
            addCriterion("reviews_count >", value, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andReviewsCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("reviews_count >=", value, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andReviewsCountLessThan(Integer value) {
            addCriterion("reviews_count <", value, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andReviewsCountLessThanOrEqualTo(Integer value) {
            addCriterion("reviews_count <=", value, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andReviewsCountIn(List<Integer> values) {
            addCriterion("reviews_count in", values, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andReviewsCountNotIn(List<Integer> values) {
            addCriterion("reviews_count not in", values, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andReviewsCountBetween(Integer value1, Integer value2) {
            addCriterion("reviews_count between", value1, value2, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andReviewsCountNotBetween(Integer value1, Integer value2) {
            addCriterion("reviews_count not between", value1, value2, "reviewsCount");
            return (Criteria) this;
        }

        public Criteria andStarRatingIsNull() {
            addCriterion("star_rating is null");
            return (Criteria) this;
        }

        public Criteria andStarRatingIsNotNull() {
            addCriterion("star_rating is not null");
            return (Criteria) this;
        }

        public Criteria andStarRatingEqualTo(Float value) {
            addCriterion("star_rating =", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotEqualTo(Float value) {
            addCriterion("star_rating <>", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingGreaterThan(Float value) {
            addCriterion("star_rating >", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingGreaterThanOrEqualTo(Float value) {
            addCriterion("star_rating >=", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingLessThan(Float value) {
            addCriterion("star_rating <", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingLessThanOrEqualTo(Float value) {
            addCriterion("star_rating <=", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingIn(List<Float> values) {
            addCriterion("star_rating in", values, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotIn(List<Float> values) {
            addCriterion("star_rating not in", values, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingBetween(Float value1, Float value2) {
            addCriterion("star_rating between", value1, value2, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotBetween(Float value1, Float value2) {
            addCriterion("star_rating not between", value1, value2, "starRating");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeIsNull() {
            addCriterion("space_type is null");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeIsNotNull() {
            addCriterion("space_type is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeEqualTo(String value) {
            addCriterion("space_type =", value, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeNotEqualTo(String value) {
            addCriterion("space_type <>", value, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeGreaterThan(String value) {
            addCriterion("space_type >", value, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("space_type >=", value, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeLessThan(String value) {
            addCriterion("space_type <", value, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeLessThanOrEqualTo(String value) {
            addCriterion("space_type <=", value, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeLike(String value) {
            addCriterion("space_type like", value, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeNotLike(String value) {
            addCriterion("space_type not like", value, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeIn(List<String> values) {
            addCriterion("space_type in", values, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeNotIn(List<String> values) {
            addCriterion("space_type not in", values, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeBetween(String value1, String value2) {
            addCriterion("space_type between", value1, value2, "spaceType");
            return (Criteria) this;
        }

        public Criteria andSpaceTypeNotBetween(String value1, String value2) {
            addCriterion("space_type not between", value1, value2, "spaceType");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCleanFeeIsNull() {
            addCriterion("clean_fee is null");
            return (Criteria) this;
        }

        public Criteria andCleanFeeIsNotNull() {
            addCriterion("clean_fee is not null");
            return (Criteria) this;
        }

        public Criteria andCleanFeeEqualTo(BigDecimal value) {
            addCriterion("clean_fee =", value, "cleanFee");
            return (Criteria) this;
        }

        public Criteria andCleanFeeNotEqualTo(BigDecimal value) {
            addCriterion("clean_fee <>", value, "cleanFee");
            return (Criteria) this;
        }

        public Criteria andCleanFeeGreaterThan(BigDecimal value) {
            addCriterion("clean_fee >", value, "cleanFee");
            return (Criteria) this;
        }

        public Criteria andCleanFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("clean_fee >=", value, "cleanFee");
            return (Criteria) this;
        }

        public Criteria andCleanFeeLessThan(BigDecimal value) {
            addCriterion("clean_fee <", value, "cleanFee");
            return (Criteria) this;
        }

        public Criteria andCleanFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("clean_fee <=", value, "cleanFee");
            return (Criteria) this;
        }

        public Criteria andCleanFeeIn(List<BigDecimal> values) {
            addCriterion("clean_fee in", values, "cleanFee");
            return (Criteria) this;
        }

        public Criteria andCleanFeeNotIn(List<BigDecimal> values) {
            addCriterion("clean_fee not in", values, "cleanFee");
            return (Criteria) this;
        }

        public Criteria andCleanFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("clean_fee between", value1, value2, "cleanFee");
            return (Criteria) this;
        }

        public Criteria andCleanFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("clean_fee not between", value1, value2, "cleanFee");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 16 22:06:49 AEST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table house
     *
     * @mbg.generated Tue Jul 16 22:06:49 AEST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}