package xyz.nuze.model;

public class HousePicUrls {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_pic_urls.id
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_pic_urls.house_id
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    private Integer houseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_pic_urls.pic_url
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    private String picUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_pic_urls.id
     *
     * @return the value of house_pic_urls.id
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_pic_urls.id
     *
     * @param id the value for house_pic_urls.id
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_pic_urls.house_id
     *
     * @return the value of house_pic_urls.house_id
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_pic_urls.house_id
     *
     * @param houseId the value for house_pic_urls.house_id
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_pic_urls.pic_url
     *
     * @return the value of house_pic_urls.pic_url
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_pic_urls.pic_url
     *
     * @param picUrl the value for house_pic_urls.pic_url
     *
     * @mbg.generated Wed Jul 31 19:55:09 AEST 2019
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }
}